[package]
name = "l5_statanys"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
# plotters = "0.3"
csv = "1.3.1"
rayon = "1.10.0"
indicatif = "0.17.9"
kiddo = "4.2.1"
plotters = "0.3.7"